
let DATA = []; let MAP = new Map(); let barChart, pieChart;
async function loadData(){ const resp = await fetch('carometro_normalizado.json'); DATA = await resp.json(); DATA.forEach(m => MAP.set((m.municipio||'').toLowerCase(), m)); const dl = document.getElementById('municipios'); dl.innerHTML = DATA.map(m => `<option value="${m.municipio}">`).join(''); }
function currency(v){ if(v==null) return 'R$ 0'; return v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}); }
function slug(s){ return (s||'').normalize('NFD').replace(/\p{Diacritic}/gu,'').replace(/[^a-z0-9]+/gi,'-').replace(/(^-|-$)/g,'').toLowerCase(); }
function fillCard(m){ const p=m.prefeito||{}; document.getElementById('nomePrefeito').textContent=`${p.nome||'Prefeito'} — ${m.municipio}`; document.getElementById('partido').textContent=p.partido||''; document.getElementById('mandato').textContent=p.mandato||''; document.getElementById('vice').textContent=p.vice||''; const c=(p.contatos||{}); document.getElementById('gabinete').textContent=c.gabinete||''; document.getElementById('prefeitura').textContent=c.prefeitura||''; document.getElementById('email').textContent=c.email_prefeitura||c.email_pessoal||''; document.getElementById('celular').textContent=c.celular||''; const img=document.getElementById('fotoPrefeito'); const asset=m.foto_asset||`prefeitos/${slug(m.municipio)}.jpg`; img.src=asset; img.onerror=()=>{ img.src='icons/icon-512.png'; }; }
function uniqueSorted(a){ return [...new Set(a.filter(Boolean))].sort(); }
function buildFilters(m){ const anos=uniqueSorted(m.repasses.map(r=>r.ano)); const tipos=uniqueSorted(m.repasses.map(r=>r.tipo)); const sits=uniqueSorted(m.repasses.map(r=>r.situacao)); fAno.innerHTML='<option value="">Ano (todos)</option>'+anos.map(a=>`<option>${a}</option>`).join(''); fTipo.innerHTML='<option value="">Tipo (todos)</option>'+tipos.map(t=>`<option>${t}</option>`).join(''); fSit.innerHTML='<option value="">Situação (todas)</option>'+sits.map(s=>`<option>${s}</option>`).join(''); }
function applyFilters(m){ const ano=fAno.value; const tipo=fTipo.value; const sit=fSit.value; return m.repasses.filter(r => (!ano || String(r.ano)===String(ano)) && (!tipo || r.tipo===tipo) && (!sit || r.situacao===sit)); }
function fillTotals(m){ const t=m.totais||{}; tDestinado.textContent=currency(t.destinado||0); tEmpenhado.textContent=currency(t.empenhado||0); tPago.textContent=currency(t.pago||0); tSaldo.textContent=currency(t.saldo||0); }
function drawCharts(m, rows){ const ctxBar=barChartEl.getContext('2d'); const ctxPie=pieChartEl.getContext('2d'); const groups={'Saúde':0,'Segurança':0,'Educação':0,'Outras':0}; rows.forEach(r=>{ const base=r.valor_pago ?? r.valor_empenhado ?? 0; groups[r.macro_area||'Outras']=(groups[r.macro_area||'Outras']||0)+base; }); const labelsBar=Object.keys(groups); const dataBar=labelsBar.map(k=>groups[k]||0); if(barChart) barChart.destroy(); barChart=new Chart(ctxBar,{type:'bar',data:{labels:labelsBar,datasets:[{label:'R$',data:dataBar}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{ticks:{callback:(v)=>currency(v)}}}}}); const sitMap={}; rows.forEach(r=>{ const base=r.valor_pago ?? r.valor_empenhado ?? 0; const k=r.situacao||'—'; sitMap[k]=(sitMap[k]||0)+base; }); const labelsPie=Object.keys(sitMap); const dataPie=labelsPie.map(k=>sitMap[k]||0); if(pieChart) pieChart.destroy(); pieChart=new Chart(ctxPie,{type:'pie',data:{labels:labelsPie,datasets:[{data:dataPie}]},options:{responsive:true,plugins:{legend:{position:'bottom'}}}}); }
function fillTable(rows){ tbody.innerHTML=rows.map(r=>`<tr><td>${r.ano||''}</td><td>${r.tipo||''}</td><td>${r.area||''}</td><td>${r.beneficiario||''}</td><td>${r.objeto||''}</td><td>${r.situacao||''}</td><td>${currency(r.valor_emenda||0)}</td><td>${currency(r.valor_empenhado||0)}</td><td>${currency(r.valor_pago||0)}</td></tr>`).join(''); }
function renderMunicipio(name){ const m=MAP.get((name||'').toLowerCase()); if(!m){ alert('Município não encontrado.'); return; } fillCard(m); fillTotals(m); buildFilters(m); const rows=applyFilters(m); drawCharts(m, rows); fillTable(rows); }
const fAno=document.getElementById('fAno'),fTipo=document.getElementById('fTipo'),fSit=document.getElementById('fSit'); const barChartEl=document.getElementById('barChart'), pieChartEl=document.getElementById('pieChart'); const tbody=document.getElementById('tbody'); const btnPDF=document.getElementById('btnPDF'); const btnBuscar=document.getElementById('btnBuscar');
btnBuscar.addEventListener('click', ()=>{ renderMunicipio(document.getElementById('municipio').value); });
[fAno,fTipo,fSit].forEach(e=> e.addEventListener('change', ()=>{ const m=MAP.get(document.getElementById('municipio').value.toLowerCase()); if(m){ const rows=applyFilters(m); drawCharts(m, rows); fillTable(rows); } }));
btnPDF.addEventListener('click', ()=>{ window.print(); });
let deferredPrompt; window.addEventListener('beforeinstallprompt',(e)=>{ e.preventDefault(); deferredPrompt=e; const btn=document.getElementById('btnInstall'); btn.hidden=false; btn.onclick=async()=>{ btn.hidden=true; deferredPrompt.prompt(); await deferredPrompt.userChoice; deferredPrompt=null; }; });
if('serviceWorker' in navigator){ window.addEventListener('load', ()=>{ navigator.serviceWorker.register('./service-worker.js'); }); }
loadData();
